name: Call Global Library 
on:
  push:
    branches:
      - main
jobs:
  preInit:
    runs-on: ubuntu-latest
    steps:
      - name: Check for properties file
        run: echo "Initialization Section"
  call-global-library:
    uses: dblucas-ops/corporate-maven-global-library/.github/workflows/mavenCICD.yml@main
    with:
      callerRepo: call-global-library
      branchName: main
      buildCmd: mvn
    secrets: inherit
